// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAScNWtCkoRMEP2t7WwxS_nGaeJHWLbeHc',
    appId: '1:968517267974:web:85729debee759ddc600987',
    messagingSenderId: '968517267974',
    projectId: 'expense-tracker-b0942',
    authDomain: 'expense-tracker-b0942.firebaseapp.com',
    storageBucket: 'expense-tracker-b0942.firebasestorage.app',
    measurementId: 'G-HP88RMK8N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6E3gzJttTn8ui2F93Ivb4o1MLmdaeSLA',
    appId: '1:968517267974:android:377f7be77ac8457e600987',
    messagingSenderId: '968517267974',
    projectId: 'expense-tracker-b0942',
    storageBucket: 'expense-tracker-b0942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0wz5YoJTFs0tzgdIY2CP0HSrv_IYWTLU',
    appId: '1:968517267974:ios:28353e738c30faeb600987',
    messagingSenderId: '968517267974',
    projectId: 'expense-tracker-b0942',
    storageBucket: 'expense-tracker-b0942.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0wz5YoJTFs0tzgdIY2CP0HSrv_IYWTLU',
    appId: '1:968517267974:ios:28353e738c30faeb600987',
    messagingSenderId: '968517267974',
    projectId: 'expense-tracker-b0942',
    storageBucket: 'expense-tracker-b0942.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAScNWtCkoRMEP2t7WwxS_nGaeJHWLbeHc',
    appId: '1:968517267974:web:51b428f68d1a2f9c600987',
    messagingSenderId: '968517267974',
    projectId: 'expense-tracker-b0942',
    authDomain: 'expense-tracker-b0942.firebaseapp.com',
    storageBucket: 'expense-tracker-b0942.firebasestorage.app',
    measurementId: 'G-EJNSHTYYDG',
  );
}
